language: python

python:
  - 2.6
  - 2.7
# - 3.3

services: postgresql

env:
  global:
# - DJANGO="x.y.z"
  - DJANGO_SETTINGS_MODULE="ponyforum.settings"
  - PYTHONPATH="/home/travis/build/ndarville/pony-forum"
  - PIP_USE_MIRRORS=true
# Last two for OS X, courtesy of stackoverflow.com/a/22697917/419005
  - CFLAGS=-Qunused-arguments
  - CPPFLAGS=-Qunused-arguments

install:
  - pip install elementtree --allow-external elementtree --allow-unverified elementtree
  - pip install -r requirements.txt
# - pip install django==$DJANGO --quiet
  - pip install coveralls radon
# - pip install pip-tools --quiet

before_script:
  - psql -c "CREATE DATABASE travisdb;" -U postgres

script:
  - sh build_forum.sh

after_success:
- pip freeze
- echo Uploading code coverage data ...; coveralls
- echo Code complexity scores:; radon cc --min B ../pony-forum

notifications:
  email:
    on_success: change
    on_failure: always

# matrix:
#   allow_failures:
#     - python: 3.3
