language: python

python:
  - 2.6
  - 2.7

services: postgresql

env:
  - DJANGO=1.4.1

before_install:
  - export DJANGO_SETTINGS_MODULE=ponyforum.settings
  - export PYTHONPATH=$HOME/builds/ndarville/pony-forum
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt
  - pip install django==$DJANGO --quiet
  - pip install psycopg2 --quiet
  - pip install pip-tools --quiet

before_script:
  - psql -c "CREATE DATABASE ponydb;" -U postgres

script:
  - python manage.py syncdb --noinput
  - python _postinstall/mkadmin.py
  - python _postinstall/definesite.py
  - python _postinstall/mkplaceholders.py

after_script:
  - pip-review
  - python manage.py test

notifications:
  email:
    on_success: change
    on_failure: always